export const Activities = [
  {activity: 'Walking',},
  {activity: 'Running',},
  {activity: 'Swimming',},
  {activity: 'Cycling',},
  {activity: 'Yoga',},
  {activity: 'Meditation',},
  {activity: 'Reading',},
  {activity: 'Cooking',},
  {activity: 'Gardening',},
  {activity: 'Dancing',},
  {activity: 'Painting',},
  {activity: 'Writing',},
  {activity: 'Playing Music',},
  {activity: 'Hiking',},
  {activity: 'Fishing',},
  {activity: 'Shopping',},
  {activity: 'Gaming',},
  {activity: 'Watching Movies',},
  {activity: 'Attending Classes',},
  {activity: 'Socializing',},
  {activity: 'Volunteering',},
  {activity: 'Photography',},
  {activity: 'Working Out',},
  {activity: 'Exploring Nature',},
  {activity: 'Traveling',},
]
